### ISSUE TITLE
Mantain state of Stateful widget on switching page

### ISSUE THREAD

**Issue by alvarofvr** [nnior/bottom_personalized_dot_bar#2]
How can we mantain the state of a Stateful Widget of a page built by the animation builder on switching page?

**Comment by nnior** [comment]
Hi @alvarofvr, if you use AnimatedSwitcher, every time you change the 'child' property, the widget will be created again. If you want to maintain the status of these widgets, you must use another solution.
For example you can use a Stack instead of the AnimatedSwitcher.

**Comment by alvarofvr** [comment]
Hi @nnior, I used a `TabBarView` then in my stateful widget put the `AutomaticKeepAliveClientMixin`  mixin.
